from __future__ import annotations
from typing import Protocol, List, Dict, Any
from records import NormRecord

class Archiver(Protocol):
    name: str
    def reset(self) -> None: ...
    def update(self, candidates: List[NormRecord]) -> None: ...
    def front(self) -> List[NormRecord]: ...
    def state(self) -> Dict[str, Any]: ...
